services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: ai-dashboard-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:4000 # your backend URL
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: ai-dashboard-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      # - MONGODB_URI=${MONGODB_URI}  # MongoDB Atlas connection string
    depends_on: []
